name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.build --tag lambda-builder:$(date +%s)
        docker volume create cargo-registry
        docker run --rm --mount type=bind,source="$(pwd)",target=/build --mount type=volume,source=cargo-registry,target=/root/.cargo/registry/ lambda-builder:$(date +%s)
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: deploy_zip
        path: deploy.zip
        retention-days: 5
